steps:
  # Build the Docker image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/build-with-vertex-ai/profmatch-fe:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/build-with-vertex-ai/profmatch-fe:latest'
      - '.'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/build-with-vertex-ai/profmatch-fe:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/build-with-vertex-ai/profmatch-fe:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'profmatch'
      - '--image=gcr.io/build-with-vertex-ai/profmatch-fe:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/build-with-vertex-ai/profmatch-fe:$COMMIT_SHA'
  - 'gcr.io/build-with-vertex-ai/profmatch-fe:latest'